[test]
# Always enable coverage
coverage = true
coveragePathIgnorePatterns = [
  "node_modules/**",
  "**/*.test.ts",
  "dist/**",
  "packages/core/dist/**",
  "packages/cli/dist/**",
  "packages/visualizer/dist/**"
]
